Victor Saldivia
Diana Dusseaux

### **Importando librerias

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### **Accediendo a dataset

In [2]:
datos = pd.read_csv("Pokemon.csv")

### **Mostrar la informacion del dataset

In [ ]:
datos.info() #info muestra la información detallada del dataset

<class 'pandas.DataFrame'>
RangeIndex: 1037 entries, 0 to 1036
Data columns (total 44 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Number                   1037 non-null   int64
 1   Name                     1037 non-null   str
 2   Type 1                   1037 non-null   str
 3   Type 2                   551 non-null    str
 4   Abilities                1037 non-null   str
 5   HP                       1037 non-null   int64
 6   Att                      1037 non-null   int64
 7   Def                      1037 non-null   int64
 8   Spa                      1037 non-null   int64
 9   Spd                      1037 non-null   int64
 10  Spe                      1037 non-null   int64
 11  BST                      1037 non-null   int64
 12  Mean                     1037 non-null   float64
 13  Standard Deviation       1037 non-null   float64
 14  Generation               1037 non-null   float64
 15  Experience type          1037 non-null   str
 16  Experience to level 100  1037 non-null   int64
 17  Final Evolution          1037 non-null   float64
 18  Catch Rate               1037 non-null   int64
 19  Legendary                1037 non-null   float64
 20  Mega Evolution           1037 non-null   float64
 21  Alolan Form              1037 non-null   float64
 22  Galarian Form            1037 non-null   float64
 23  Against Normal           1037 non-null   float64
 24  Against Fire             1037 non-null   float64
 25  Against Water            1037 non-null   float64
 26  Against Electric         1037 non-null   float64
 27  Against Grass            1037 non-null   float64
 28  Against Ice              1037 non-null   float64
 29  Against Fighting         1037 non-null   float64
 30  Against Poison           1037 non-null   float64
 31  Against Ground           1037 non-null   float64
 32  Against Flying           1037 non-null   float64
 33  Against Psychic          1037 non-null   float64
 34  Against Bug              1037 non-null   float64
 35  Against Rock             1037 non-null   float64
 36  Against Ghost            1037 non-null   float64
 37  Against Dragon           1037 non-null   float64
 38  Against Dark             1037 non-null   float64
 39  Against Steel            1037 non-null   float64
 40  Against Fairy            1037 non-null   float64
 41  Height                   1037 non-null   float64
 42  Weight                   1037 non-null   float64
 43  BMI                      1037 non-null   float64
dtypes: float64(29), int64(10), str(5)
memory usage: 356.6 KB

In [ ]:
datos.describe() #con describe se obtiene el promedio, numero max, num min

,Number,HP,Att,Def,Spa,Spd,Spe,BST,Mean,Standard Deviation,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
count,1037.000000,1037.000000,1037.000000,1037.000000,1037.000000,1037.00000,1037.000000,1037.000000,1037.000000,1037.000000,...,1037.000000,1037.000000,1037.000000,1037.000000,1037.000000,1037.000000,1037.000000,1037.000000,1037.000000,1037.000000
mean,439.248795,69.928640,80.550627,74.590164,72.922854,72.16297,68.648023,438.803279,73.133880,20.016684,...,1.003375,1.241080,1.025554,0.974928,1.075458,0.990598,1.093298,1.287560,72.022662,136.261813
std,262.685812,26.185718,32.489062,30.874588,32.744504,27.57747,30.206888,120.525770,20.087628,10.807725,...,0.613643,0.703415,0.577550,0.377131,0.475036,0.511306,0.534216,1.389171,132.784615,3104.156391
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.00000,5.000000,175.000000,29.166667,0.000000,...,0.250000,0.250000,0.000000,0.000000,0.250000,0.250000,0.250000,0.100000,0.100000,0.000000
25%,211.000000,50.000000,55.000000,50.000000,50.000000,50.00000,45.000000,330.000000,55.000000,12.801910,...,0.500000,1.000000,1.000000,1.000000,1.000000,0.500000,1.000000,0.600000,9.000000,18.600000
50%,434.000000,67.000000,78.000000,70.000000,65.000000,70.00000,65.000000,460.000000,76.666667,18.484228,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,29.800000,28.400000
75%,668.000000,83.000000,100.000000,90.000000,95.000000,90.00000,90.000000,515.000000,85.833333,24.830537,...,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.600000,72.000000,42.200000
max,900.000000,255.000000,190.000000,230.000000,194.000000,230.00000,200.000000,780.000000,130.000000,103.215659,...,4.000000,4.000000,4.000000,2.000000,4.000000,4.000000,4.000000,20.000000,999.900000,99990.000000

### **Imprimir la cantidad de filas duplicadas

In [5]:
filas_duplicadas = datos[datos.isnull().any(axis=1.0)]
filas_duplicadas #eliminando duplicados de las filas

,Number,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
4,4,Charmander,Fire,NaN,"['Blaze', 'Solar Power']",39,52,43,60,50,...,0.5,2.0,1.0,1.0,1.0,0.5,0.5,0.6,8.5,23.6
5,5,Charmeleon,Fire,NaN,"['Blaze', 'Solar Power']",58,64,58,80,65,...,0.5,2.0,1.0,1.0,1.0,0.5,0.5,1.1,19.0,15.7
9,7,Squirtle,Water,NaN,"['Rain Dish', 'Torrent']",44,48,65,50,64,...,1.0,1.0,1.0,1.0,1.0,0.5,1.0,0.5,9.0,36.0
10,8,Wartortle,Water,NaN,"['Rain Dish', 'Torrent']",59,63,80,65,80,...,1.0,1.0,1.0,1.0,1.0,0.5,1.0,1.0,22.5,22.5
11,9,Blastoise,Water,NaN,"['Rain Dish', 'Torrent']",79,83,100,85,105,...,1.0,1.0,1.0,1.0,1.0,0.5,1.0,1.6,85.5,33.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1026,895,Regidrago,Dragon,NaN,"[""Dragon's Maw""]",200,100,50,100,50,...,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.1,200.0,45.4
1027,896,Glastrier,Ice,NaN,['Chilling Neigh'],100,145,130,65,110,...,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.2,800.0,165.3
1028,897,Spectrier,Ghost,NaN,['Grim Neigh'],100,65,60,145,80,...,0.5,1.0,2.0,1.0,2.0,1.0,1.0,2.0,44.5,11.1
1033,900,Kangaskhan,Normal,NaN,"['Early Bird', 'Inner Focus', 'Scrappy']",105,95,80,40,80,...,1.0,1.0,0.0,1.0,1.0,1.0,1.0,2.2,80.0,16.5
1034,25,Pikachu,Electric,NaN,"['Lightning Rod', 'Static']",35,55,40,50,50,...,1.0,1.0,1.0,1.0,1.0,0.5,1.0,0.4,6.0,37.5

### **Contar los valores nulos existentes

In [ ]:
datos.isnull() #visualizando valores duplicados

,Number,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1032,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1033,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1034,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1035,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1036,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
print(f"La cantidad de columnas y filas son {datos.shape}") #Shape nos muestra las filas y columnas del dataset

La cantidad de columnas y filas son (1037, 44)

### **Crear la nueva variable sin datos nulos

In [ ]:
datos_sin_nulos = datos.dropna() #Con dropna se eliminan los duplicados
datos_sin_nulos #nueva variable sin datos nulos

,Number,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0
2,3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82,83,100,100,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,2.0,100.0,25.0
3,3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100,123,122,120,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,2.4,155.5,27.0
6,6,Charizard,Fire,Flying,"['Blaze', 'Solar Power']",78,84,78,109,85,...,0.25,4.0,1.0,1.0,1.0,0.5,0.5,1.7,90.5,31.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1030,898,Calyrex Ice Rider,Psychic,Ice,['As One'],100,165,150,85,130,...,2.00,2.0,2.0,1.0,2.0,2.0,1.0,2.4,809.1,140.5
1031,898,Calyrex Shadow Rider,Psychic,Ghost,['As One'],100,85,80,165,100,...,1.00,1.0,4.0,1.0,4.0,1.0,1.0,2.4,53.6,9.3
1032,899,Alolan Raichu,Electric,Psychic,['Surge Surfer'],60,85,50,95,85,...,2.00,1.0,2.0,1.0,2.0,0.5,1.0,0.7,21.0,42.9
1035,6,Charizard,Fire,Flying,"['Blaze', 'Solar Power']",78,84,78,109,85,...,0.25,4.0,1.0,1.0,1.0,0.5,0.5,1.7,90.5,31.3
1036,389,Torterra,Grass,Ground,"['Overgrow', 'Shell Armor']",95,109,105,75,85,...,2.00,0.5,1.0,1.0,1.0,1.0,1.0,2.2,310.0,64.0

### **Crear una función que permita filtrar los pokemon de tipo fuego

In [ ]:
def filtro_fuego(Fire): #función para acceder a los pokemones de fuego
    
    return "Fire" in Fire

pokemon_fuego = datos_sin_nulos[datos_sin_nulos]["Type_1"]==["Fire"]

#Mostrar los 20 pokemones de la lista
pokemon_fuego.head(20)

TypeError: Boolean array expected for the condition, not int64

In [ ]:
def nivel_ataque(int): #Creando función para clasificar los niveles de ataque
    return "att" in int
#función nivel de ataque

In [ ]:
Promedio = pokemon_fuego.mean() #la función mean nos permite obtener el promedio
Promedio

### **Creando grafico barra

In [ ]:
plt.bar(pokemon_fuego,nivel_ataque) #con bar estamos generando un grafico de barra
plt.title("Top 10 de Pokemon y su nivel de ataque") 
plt.xlabel("Pokemon")
plt.ylabel("Nivel de ataque")
plt.show()

### **Creando grafico de lineas

In [ ]:
plt.plot(pokemon_fuego.index, pokemon_fuego.values,
         marker = "O",
         linestyle = "-",
         color = "blue")

plt.title("Pokemones de fuego")
plt.xlabel("Pokemon")
plt.ylabel("Cantidad")
plt.show()

In [ ]:
plt.plot(filtro_fuego.index, filtro_fuego.evalues,
         marker = "o",
         linestyles = "-",
         color = "blue")
plt.title("Pokemones de tipo fuego")
plt.xlabel("Tipo de Pokemon")
plt.ylabel("Cantidad de pokemon")
plt.show()